hash-format = "sha256"

[[files]]
file = "mods/advent-of-ascension-nevermine.pw.toml"
hash = "543f3c3bbbba8b101dcd35891dc484bd2c6edf7f7a6cc0d59567a8b6c6c80c7f"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "66e34a1e0bfd3a9ee39b1f58b1af494b843fa22979a28207f397e4710547b9d2"
metafile = true

[[files]]
file = "mods/armortech.pw.toml"
hash = "ecc71c68c9bb8ee95bdfbb720eb2e414187a8ce132a3c9bb09fc1bd011e38f9b"
metafile = true

[[files]]
file = "mods/baubles.pw.toml"
hash = "2cc5f913400c0dfe460173edd1e5d9475a09774caf228f41c3e39eba252a7a19"
metafile = true

[[files]]
file = "mods/bdlib.pw.toml"
hash = "d89dd31193a74be6ea9fce495bb85ee31028ea299c1d2d0741607c0347ef2127"
metafile = true

[[files]]
file = "mods/betterfps.pw.toml"
hash = "3be157f6924a51edca3ade05d9a2c9e16e13e376c874fa6eecb11d0bf6c0a2db"
metafile = true

[[files]]
file = "mods/binnies-mods.pw.toml"
hash = "9d3285a142931c24a2e9373985cb1ca645526aa97e54da5c34f21584c0648e26"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "a6f2a5c57e847e8a587ca95caf23fff6d91aff86828d764496143a35a30773ed"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "9b29f8c649940c076771dae2b5de364eaa3b44d65a5f993bdc3482623c82e9b8"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "96de7b241688c8771621d9ef3dcc4eb565389739196334bea745043375dbc03a"
metafile = true

[[files]]
file = "mods/botanic-additions.pw.toml"
hash = "c5a34d235726a2bcc24fb851fb73c785a98427cfccbbcc483f9f040f287ecc4d"
metafile = true

[[files]]
file = "mods/brandons-core.pw.toml"
hash = "e6b6f908221c3ff5f821e0f648a05f037ca100a242fb3d0122db9209e2531be2"
metafile = true

[[files]]
file = "mods/buildcraft.pw.toml"
hash = "ae1102797c17f21f72397fb6e66145c1d7427fa825e771e9c314ba66b8682f54"
metafile = true

[[files]]
file = "mods/chameleon.pw.toml"
hash = "305815006195c0647af38ea5d8c03cd6c652c77bf975e3e967b754bc3b9ac569"
metafile = true

[[files]]
file = "mods/chicken-chunks-1-8.pw.toml"
hash = "8c1cd98cbd76ccba330c24575c02edd0ede38a08330a843f9874efee8a1738dd"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "49d0ddb311fa9fe9b193996de176a92e0ab2b26b4030344ae80cff4584fdadc4"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
hash = "430820ab4fc97024a7c5c188555c57e6fa22f33fe3d5f98d2a75254a0bd07633"
metafile = true

[[files]]
file = "mods/draconic-evolution.pw.toml"
hash = "ea5eb18a73607ffd04a198f654209855fb831abdcac646fe2411d77b0dea2f9e"
metafile = true

[[files]]
file = "mods/ender-io.pw.toml"
hash = "90b8f96283a98af81b8a4826e9544ec4326cdcadc72930a76e1c19bc46fdb443"
metafile = true

[[files]]
file = "mods/endercore.pw.toml"
hash = "f41bf1c7154b656b303822ea5fe596d4afc97c5712facf03c244d08ae9c129d3"
metafile = true

[[files]]
file = "mods/energy-converters.pw.toml"
hash = "3fb33d0b22cb9f434fc033670798f41ffd5eb1d5cc0187b175ead7dfec445f63"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "cd43c995d3b2f2095d27c5ca40cef005adff2dc07a827c7b9a6aff4a14438ffe"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "fcde0ee8bff608d544d39815dae2b3c76775eb763122c8713d7e3bc97de388fd"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "d856a3027bb9f9d54c0ea2e02e6150510eeebd240bbb240779cdf0c27607110b"
metafile = true

[[files]]
file = "mods/findme.pw.toml"
hash = "121e1e09c5ed36fba71199f5976589f26c5ff8ae8f4d43f0398c03b62c8a9196"
metafile = true

[[files]]
file = "mods/foamfix-optimization-mod.pw.toml"
hash = "9ebf99a09414c38e4959b828266d83d3983366e1694d0bb901125a85121e97de"
metafile = true

[[files]]
file = "mods/forestry.pw.toml"
hash = "c165f7aba2c94ad1d1b42cb769c3bd468dfcb369cf631509b486aa37e9ed8bfb"
metafile = true

[[files]]
file = "mods/forge-backpacks.pw.toml"
hash = "de9392eadb5028ad2c588a9e6b422cf521d87da08d3126a15a248834e81be468"
metafile = true

[[files]]
file = "mods/fps-reducer.pw.toml"
hash = "2571263ec4228ca6c6d2cdbf677bbb7b07622382163f606630304696ba5d4abc"
metafile = true

[[files]]
file = "mods/gendustry.pw.toml"
hash = "466b15cefb457971c6b7c3f8c351c22abeb0bfd6baaba60e5b3d3159910fb3ff"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
hash = "157f6e6aa64ae6cf9da95be6b45dc54bf35c4e89e1c9f78866b1dc1821063b47"
metafile = true

[[files]]
file = "mods/gregtech-ce-unofficial.pw.toml"
hash = "c02a97d59ab1cc726e173bac0c456da17938724fcd124d26329302d8fc2b9b5d"
metafile = true

[[files]]
file = "mods/growthcraft-community-edition.pw.toml"
hash = "0ce3bd53cb0cd4384c7b7592fd9453884518fa3c724b70f1a8d338bba5fe6235"
metafile = true

[[files]]
file = "mods/hammer-lib.pw.toml"
hash = "cf4618ad1b389bdbcfd9393b5899a08e53534dd0523d0b2de6c32651c84b78b8"
metafile = true

[[files]]
file = "mods/ido.pw.toml"
hash = "05522e04504a3d134d6c6ddf8bc7f39c9740b0a39925befb3e486c3675dc156e"
metafile = true

[[files]]
file = "mods/inventory-tweaks.pw.toml"
hash = "260f17df66f36ac79ab67ba721c28f868c09a32c9c858649f9971f9147cf6e21"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
hash = "f5e51601becf4c9f8878530d40cd2ecf232e89e5d9fae6218959a15eee12417d"
metafile = true

[[files]]
file = "mods/jei-bees.pw.toml"
hash = "5217258c2ca6fedd22cc77af64c9c5572b871df90b737d67a0b646020d69781f"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "49cfa6cc9199acf8160d8d4d5c7c0be5f6b5ac2d3e113a7d1f27a91fb237fd9c"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "34bcd62bca78729d9c295bb8d7cbfde2239af84c86719744a4e8c0af7e69f150"
metafile = true

[[files]]
file = "mods/less-lag.pw.toml"
hash = "a034996234d836f6c89fd94ced046a54c5b1ffa7a8a4eef5caf269bc27178aab"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "3b5ef81c27805786f2b7e53d12bbb5a7a9ec8eacf8c005dd3f657f731480796a"
metafile = true

[[files]]
file = "mods/more-bees.pw.toml"
hash = "22036c4bbe2928fe71f84d94375ce48b0ecd669dd32be17f39b792935790e418"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "30746e92b44351d3365fa5aa6e43b623476c91116fb8b9f88b7233339d3c9f43"
metafile = true

[[files]]
file = "mods/neat.pw.toml"
hash = "799a1e945853fb75bfa3aaa45a1d120714f62c619535cb0e15b6d89af1d34fe4"
metafile = true

[[files]]
file = "mods/obfuscate.pw.toml"
hash = "056799cc0aa43fa412f48cc524a7f83336bfb0e2f1c0e5084a4b6ca6b1fe0454"
metafile = true

[[files]]
file = "mods/official-divinerpg.pw.toml"
hash = "51ed566a2c7887b34a2da9324539c5a14efd7c4ce5ec0862b184102859ad1538"
metafile = true

[[files]]
file = "mods/omlib.pw.toml"
hash = "b26dcb762a85ace42d3f3c2917d2eaf0dd759ee5e355bb986b07f723249dd4b1"
metafile = true

[[files]]
file = "mods/openmodularturrets.pw.toml"
hash = "8bfb0749eb020348649c1c7abf3e5b980ac35a52508a52fb329c19135b55b869"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "bf3ab3065a3d3cbf04b5632a6088c9db9381c54c2149c8713748dde1b5859472"
metafile = true

[[files]]
file = "mods/performant.pw.toml"
hash = "5865f55ac3ee06486892780710061e5a93d803c16bfaa346520b4203c8f124fc"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "929442340bcaa421711871e3fa359e7d02ed9f4438312c803363eb1ec9460782"
metafile = true

[[files]]
file = "mods/reborncore.pw.toml"
hash = "210ac01b61f9b387b1406c05b788d2dafae7c261756d814b27ba99400391865b"
metafile = true

[[files]]
file = "mods/redstone-flux.pw.toml"
hash = "c4730aa68206dba3e9fe24d60b107d914d202ba5e3f5842f06d3fa40ec05d06c"
metafile = true

[[files]]
file = "mods/reliquary-reincarnations.pw.toml"
hash = "1b4a0a19615a8b8ed0d78ddfd05fa3ee59f7050a8a4490de0e800115c0b66885"
metafile = true

[[files]]
file = "mods/shadowfacts-forgelin.pw.toml"
hash = "3fc16d41893803e4afd4ddb2b981ed360081cea152a21f9783aac3bae182f6fc"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "1976cfb3222e1f141aa56af5824be673771a9db93b49c7e48fa2cca3f58aef02"
metafile = true

[[files]]
file = "mods/surge.pw.toml"
hash = "76364bbc6e5ab454bdbd76fa3502bdee90c0bb842f6b405ed60f1d33c76053ee"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
hash = "a54a03942ed382d2d195f63e386c5bff4ef6c521b3b1a3d2a1d8fa4283e2c99b"
metafile = true

[[files]]
file = "mods/thaumcraft-6-aspects-for-jei.pw.toml"
hash = "fb169d97b00248f31e47862759105df2a851aff28391fc344fc26c5eabfde949"
metafile = true

[[files]]
file = "mods/thaumcraft.pw.toml"
hash = "642fb95aa39530f0b662148d8f5357ea7cfc48312216eced5251d7337f80c9cd"
metafile = true

[[files]]
file = "mods/thaumic-jei.pw.toml"
hash = "3dcef794ba03565241c47808178e96d5d8db82d4a9659d2a340fd3966ac107a1"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "7af0b8a8e634eab7ecd9e6401ce3c71d6ec1c2c5dae078dee5a526898f88c72c"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "3e6cb5fcf2c9c4254ca778c8fc61b4d05e895c111c2a98fb6c0b2bc44922e3f2"
metafile = true

[[files]]
file = "mods/totemic.pw.toml"
hash = "e1dd6679beb37914b4fbe2441ee57a21eb381798ff871ce134adcf2ac6ad7794"
metafile = true

[[files]]
file = "mods/unidict.pw.toml"
hash = "b7efcef0724d49de5e486cf957b8600c4df388a64575c7fd99d5a0a20499e22d"
metafile = true

[[files]]
file = "mods/vics-modern-warfare-mod.pw.toml"
hash = "fa6c91ce9030728003ea87cf27d83b60d6871d895a4a30bf6aca254699219631"
metafile = true

[[files]]
file = "mods/wanionlib.pw.toml"
hash = "7eb42ae64d048660ef6f7c1f61ce32aebae59174f9fbfa45d74aea5afc28fb43"
metafile = true
