name = "Modtd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d776778b83327064f300af66403887e374231c10fbbfbb43272bef42954a1ad6"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
